### ISSUE TITLE
解决磁力链接无法解析

### ISSUE THREAD

**Issue by fangxy926** [lt94/MovieHeavens#17]
好奇为什么会有两个相同的链接？
![](https://user-images.githubusercontent.com/23739775/73642904-869dda80-46ad-11ea-9e50-05871e0f98c8.png)

看到[这里](https://github.com/lt94/MovieHeavens/blob/e4627e7901d3354e97ca509ff5f6588994ca5faf/movieSource/MovieHeaven.py#L116)的代码，发现有点不对。磁力链接为什么还用ftp_down_pattern去正则匹配

修改后

```python
magnet_url_list = magnet_down_pattern.findall(down_page_content)
```

修改后能够返回磁力链接，但是链接还有问题。和正常的磁力链接相比，匹配的结果多了`amp;`字符

![image](https://user-images.githubusercontent.com/23739775/73649239-527ce680-46ba-11ea-8fc3-bf04d643cc50.png)
用replace函数将`amp;`替换成空

```python
download_url_list.append(magnet_url_list[0].replace('amp;', ''))
```

修改后正常下载
![image](https://user-images.githubusercontent.com/23739775/73649252-5b6db800-46ba-11ea-82b4-95839439f446.png)

**Comment by lt94** [comment]
@fangxy926 可以提个pr😄
