### ISSUE TITLE
安装PyInstaller出现错误“ ModuleNotFoundError: No module named 'PyInstaller'”？

### ISSUE THREAD

**Issue by colemanlee** [lt94/MovieHeavens#8]
OS version:Microsoft Windows 10 version 1803
Python version:Python 3.7.2

> $> python3 -m pip install PyInstaller
> Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
> Collecting PyInstaller
> Downloading https://mirrors.aliyun.com/pypi/packages/03/32/0e0de593f129bf1d1e77eed562496d154ef4460fd5cecfd78612ef39a0cc/PyInstaller-3.4.tar.gz (3.5MB)
> 100% |████████████████████████████████| 3.5MB 1.6MB/s
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   Complete output from command "D:\Program Files (x86)\Python\Python37-32\python3.exe" "D:\Program Files (x86)\Python\Python37-32\lib\site-packages\pip\_vendor\pep517\_in_process.py" get_requires_for_build_wheel C:\Users\JEFFLE~1\AppData\Local\Temp\tmp7nj6_0ug:
>   Traceback (most recent call last):
>     File "D:\Program Files (x86)\Python\Python37-32\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 207, in <module>
>       main()
>     File "D:\Program Files (x86)\Python\Python37-32\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 197, in main
>       json_out['return_val'] = hook(**hook_input['kwargs'])
>     File "D:\Program Files (x86)\Python\Python37-32\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 54, in get_requires_for_build_wheel
>       return hook(config_settings)
>     File "C:\Users\JEFFLE~1\AppData\Local\Temp\pip-build-env-lw5je0z7\overlay\Lib\site-packages\setuptools\build_meta.py", line 115, in get_requires_for_build_wheel
>       return _get_build_requires(config_settings, requirements=['wheel'])
>     File "C:\Users\JEFFLE~1\AppData\Local\Temp\pip-build-env-lw5je0z7\overlay\Lib\site-packages\setuptools\build_meta.py", line 101, in _get_build_requires
>       _run_setup()
>     File "C:\Users\JEFFLE~1\AppData\Local\Temp\pip-build-env-lw5je0z7\overlay\Lib\site-packages\setuptools\build_meta.py", line 85, in _run_setup
>       exec(compile(code, __file__, 'exec'), locals())
>     File "setup.py", line 20, in <module>
>       from PyInstaller import __version__ as version, HOMEPATH, PLATFORM
>   ModuleNotFoundError: No module named 'PyInstaller'
> 
>   ----------------------------------------
> Command ""D:\Program Files (x86)\Python\Python37-32\python3.exe" "D:\Program Files (x86)\Python\Python37-32\lib\site-packages\pip\_vendor\pep517\_in_process.py" get_requires_for_build_wheel C:\Users\JEFFLE~1\AppData\Local\Temp\tmp7nj6_0ug" failed with error code 1 in C:\Users\JEFFLE~1\AppData\Local\Temp\pip-install-51r2xxed\PyInstaller

**Comment by colemanlee** [comment]
> 你的 pip 是不是更新了?, 好像有类似问题: [pyinstaller/pyinstaller#4006](https://github.com/pyinstaller/pyinstaller/issues/4006), [pypa/pip#6163](https://github.com/pypa/pip/issues/6163)

是的，更新到了最新的19.1；我搜索看看有没有办法解决。

**Comment by lt94** [comment]
好的~😄

**Comment by sh1018727638** [comment]
请问这个问题是否有解决办法，我的pip已经更新到了19.0.1

**Comment by colemanlee** [comment]
> 请问这个问题是否有解决办法，我的pip已经更新到了19.0.1

#### 我这两天尝试运行时又没出现```pip 19.0.1```或```No module named 'PyInstaller'```这种错误了，出现了新的错误如下：

> \# python3 movies.py
> Traceback (most recent call last):
>   File "movies.py", line 3, in <module>
>     from PyQt4.QtGui import *
> ModuleNotFoundError: No module named 'PyQt4'

#### 然后我尝试安装PyQt4库，出现错误如下，找不到PyQt4库：
> \# python3 -m pip install PyQt4
> Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
> Collecting PyQt4
>   Could not find a version that satisfies the requirement PyQt4 (from versions: )
> No matching distribution found for PyQt4

#### 但是在PyPi官网又有这个库，不知道怎么去安装：[https://pypi.org/project/PyQt4/](https://pypi.org/project/PyQt4/)
![pic_0201233115](https://user-images.githubusercontent.com/10258421/52132172-8bcee080-2679-11e9-9978-0818ed068c55.jpg)

#### 再然后我想从[https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyqt4](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyqt4)直接下载PyQt4的whl文件[https://download.lfd.uci.edu/pythonlibs/r5uhg2lo/PyQt4-4.11.4-cp37-cp37m-win_amd64.whl](https://download.lfd.uci.edu/pythonlibs/r5uhg2lo/PyQt4-4.11.4-cp37-cp37m-win_amd64.whl)直接本地安装，依然失败说不支持此平台，如下所示：
> \# pip3 install PyQt4-4.11.4-cp37-cp37m-win_amd64.whl
> PyQt4-4.11.4-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.

我真不知道怎么继续解决这个问题了，你们知道吗（主要是先安装上PyQt4）。
我的OS Version: Microsoft Windows® 10 version1803。

**Comment by lt94** [comment]
试一下:  ```python3 -m pip install pip==xxx``` ?

**Comment by sh1018727638** [comment]
出现了如下错误：
Could not find a version that satisfies the requirement pip==pyinstaller (from
 versions: 0.2, 0.2.1, 0.3, 0.3.1, 0.4, 0.5, 0.5.1, 0.6, 0.6.1, 0.6.2, 0.6.3, 0.
7, 0.7.1, 0.7.2, 0.8, 0.8.1, 0.8.2, 0.8.3, 1.0, 1.0.1, 1.0.2, 1.1, 1.2, 1.2.1, 1
.3, 1.3.1, 1.4, 1.4.1, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 6.0, 6.0.1
, 6.0.2, 6.0.3, 6.0.4, 6.0.5, 6.0.6, 6.0.7, 6.0.8, 6.1.0, 6.1.1, 7.0.0, 7.0.1, 7
.0.2, 7.0.3, 7.1.0, 7.1.1, 7.1.2, 8.0.0, 8.0.1, 8.0.2, 8.0.3, 8.1.0, 8.1.1, 8.1.
2, 9.0.0, 9.0.1, 9.0.2, 9.0.3, 10.0.0b1, 10.0.0b2, 10.0.0, 10.0.1, 18.0, 18.1, 1
9.0, 19.0.1)
No matching distribution found for pip==pyinstaller

**Comment by lt94** [comment]
@sh1018727638 后面是 pip==(pip的版本号) 把 pip 降级一下，然后再安装 pyqt4

**Comment by sh1018727638** [comment]
好的，我已经升级了pip到19.0.1，感谢答疑！
